#!/usr/bin/env bash
# pi-worktree.sh — create and clean git worktrees for Pi dispatch sessions.
#
# This is the generalized hoist of the worktree lifecycle proven in context-flow
# (cf-pi-worktree.sh). It accepts all inputs as explicit named parameters — no
# dependency on any cf session environment loader or convention.
#
# Usage:
#   pi-worktree.sh create \
#     --repo_root    <path>   git repository root (caller-supplied, not derived)
#     --branch_name  <name>   branch to create in the worktree
#     --base_ref     <sha>    commit sha to base the branch on
#     --base_branch  <name>   base branch name (for merge-base diff)
#     --work_path    <path>   where the worktree will be created
#     --diff_out     <path>   where cleanup captures the diff
#     --cleanup_out  <path>   script file to append the cleanup block to
#     --rundir-file  <path>   file whose CONTENTS will be the RUNDIR at cleanup time
#                             (the literal path is frozen at create; contents are
#                             read by the cleanup script at runtime after dispatch)
#
#   pi-worktree.sh clean <cleanup_out>
#     Run a cleanup script generated by a prior create call.
#
# Exit codes:
#   0  success (or idempotent re-entry)
#   1  general error
#   2  git identity not configured (DEC-1)

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ---------------------------------------------------------------------------
# Subcommand dispatch
# ---------------------------------------------------------------------------
subcmd="${1:-}"
shift || true

case "$subcmd" in
  create) ;;
  clean)
    cleanup_script="${1:?usage: pi-worktree.sh clean <cleanup_out>}"
    bash "$cleanup_script"
    exit $?
    ;;
  *)
    echo "pi-worktree: usage: pi-worktree.sh create|clean ..." >&2
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# Parse named parameters for `create`
# ---------------------------------------------------------------------------
repo_root=""
branch_name=""
base_ref=""
base_branch=""
work_path=""
diff_out=""
cleanup_out=""
rundir_file=""

while [ $# -gt 0 ]; do
  case "$1" in
    --repo_root)    repo_root="$2";    shift 2 ;;
    --branch_name)  branch_name="$2";  shift 2 ;;
    --base_ref)     base_ref="$2";     shift 2 ;;
    --base_branch)  base_branch="$2";  shift 2 ;;
    --work_path)    work_path="$2";    shift 2 ;;
    --diff_out)     diff_out="$2";     shift 2 ;;
    --cleanup_out)  cleanup_out="$2";  shift 2 ;;
    --rundir-file)  rundir_file="$2";  shift 2 ;;
    *) echo "pi-worktree: unknown param: $1" >&2; exit 1 ;;
  esac
done

# Validate required params
for _param in repo_root branch_name base_ref base_branch work_path diff_out cleanup_out rundir_file; do
  eval "_val=\"\${${_param}}\""
  if [ -z "$_val" ]; then
    echo "pi-worktree: missing required param --${_param//_/-}" >&2
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Require git (DEC-3): the primitive always expects a git repository.
# ---------------------------------------------------------------------------
if ! git -C "$repo_root" rev-parse --git-dir >/dev/null 2>&1; then
  echo "pi-worktree: $repo_root is not a git repository (scratch mode not supported)" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Idempotent re-entry (H-C): if $work_path is already a live worktree, exit 0.
# On-disk check, not env-grep.
# ---------------------------------------------------------------------------
if [ -d "$work_path" ] && git -C "$work_path" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "pi-worktree: $work_path is already a live worktree — no-op" >&2
  echo "$work_path"
  exit 0
fi

# ---------------------------------------------------------------------------
# Git-identity check (DEC-1): fail fast before mid-lifecycle "who are you" error.
# Mirror cf-pi-worktree.sh:49-61 exactly (same wording per OC-4).
# ---------------------------------------------------------------------------
if ! git -C "$repo_root" config user.email >/dev/null 2>&1 && \
   ! git config --global user.email >/dev/null 2>&1; then
  cat >&2 <<'MSG'
cf-pi-worktree: git user.email is not configured.
Per-contract commits in $WORK will fail. Set identity before re-running /cf:
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
(Or set in this repo: drop `--global`.)
MSG
  exit 2
fi

# ---------------------------------------------------------------------------
# Create the worktree on the named branch (OWD-B: one worktree, one branch).
# ---------------------------------------------------------------------------
git -C "$repo_root" worktree add -B "$branch_name" "$work_path" "$base_ref" >&2

# ---------------------------------------------------------------------------
# Append the cleanup block to cleanup_out.
#
# Heredoc-scope invariant: every variable in this block must be EITHER
#   (a) frozen as a create-time literal (unescaped $VAR — expanded NOW), OR
#   (b) defined by the cleanup script itself before use (escaped \$VAR).
#
# Create-time literals (frozen):
#   $work_path, $repo_root, $diff_out, $base_branch, $base_ref, $rundir_file
#   (the LITERAL PATH of the rundir-file, not its contents)
#
# Run-time reads (escaped):
#   \$_rundir   — contents of rundir_file at cleanup time (the actual RUNDIR)
#   \$_pgid     — contents of $RUNDIR/pi.pgid at cleanup time
#   \$_mb, \$_diff_base — merge-base computation at cleanup time
#
# The RUNDIR path is NOT known at create time (dispatch hasn't run yet).
# Instead, we freeze the rundir_file PATH as a literal. At cleanup time,
# the script reads the file contents to get the actual RUNDIR — this is
# the create-time-literal-freeze pattern from EX-12/H-A.
# ---------------------------------------------------------------------------

# Freeze diff-base values as create-time literals.
_diff_base_fallback="${base_ref:-HEAD}"
_diff_base_branch="${base_branch:-}"

# Absolute path to pi-stop.sh (sibling in scripts/).
_pi_stop="$SCRIPT_DIR/pi-stop.sh"

cat >> "$cleanup_out" <<CLEANUP_EOF
# cleanup block for worktree: $work_path
# generated by pi-worktree.sh create at $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Step 1: read RUNDIR from the frozen rundir-file path (create-time literal).
_rundir="\$(cat "$rundir_file" 2>/dev/null || true)"

# Step 2: group-kill via the frozen pi-stop.sh primitive.
if [ -n "\$_rundir" ] && [ -f "\$_rundir/pi.pgid" ]; then
  _pgid="\$(cat "\$_rundir/pi.pgid" 2>/dev/null || true)"
  bash "$_pi_stop" "\$_rundir" >/dev/null 2>&1 || true

  # Step 3: confirm-dead poll — kill-confirm BEFORE worktree remove (EX-D1).
  # Bounded: max 60 iterations * 0.5s = 30s.
  if [ -n "\$_pgid" ]; then
    _i=0
    until ! kill -0 "\$_pgid" 2>/dev/null; do
      sleep 0.5
      _i=\$((_i + 1))
      [ "\$_i" -ge 60 ] && break
    done
  fi
fi

# Step 4: capture diff before removal (commit-or-discard guard, EX-8).
git -C "$work_path" add --intent-to-add -- . 2>/dev/null || true
_diff_base="$_diff_base_fallback"
if [ -n "$_diff_base_branch" ]; then
  _mb="\$(git -C "$work_path" merge-base HEAD "$_diff_base_branch" 2>/dev/null || true)"
  [ -n "\$_mb" ] && _diff_base="\$_mb"
fi
git -C "$work_path" diff "\$_diff_base" > "$diff_out" 2>/dev/null || true

# Step 5: remove the worktree (only after confirmed death).
git -C "$repo_root" worktree remove --force "$work_path" 2>/dev/null || true
CLEANUP_EOF

echo "$work_path"
