#!/usr/bin/env bash
# Build file-touch graph from contracts.json, compute connected components,
# emit shards.json with per-group contract+file listings + fan_out_count.
# Also seeds $FLOW_SESSION/shards/<id>/ skeleton dirs with per-shard env.sh.
#
# Usage:   cf-pi-shard.sh FLOW_SESSION
# Output:  $FLOW_SESSION/shards.json
#          $FLOW_SESSION/shards/<id>/env.sh   (one per shard; inherits FLOW_SESSION's env)
# Exit:    0 on success, 2 usage, 3 contracts.json missing/malformed, 4 jq missing
#
# Shard ids are sequential letters A, B, C ... matching the order of group emission.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=cf-pi-env.sh
. "$SCRIPT_DIR/cf-pi-env.sh"

if [ $# -ne 1 ]; then
  echo "Usage: cf-pi-shard.sh FLOW_SESSION" >&2
  exit 2
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "cf-pi-shard.sh: jq is required but not installed" >&2
  exit 4
fi

flow_session="$1"
load_cf_flow_env "$flow_session"

if [ ! -f "$CONTRACTS_FILE" ]; then
  echo "cf-pi-shard.sh: contracts.json not found: $CONTRACTS_FILE" >&2
  exit 3
fi

# Sanity: schema_version present.
if ! jq -e '.schema_version' "$CONTRACTS_FILE" >/dev/null 2>&1; then
  echo "cf-pi-shard.sh: contracts.json missing schema_version" >&2
  exit 3
fi

# Compute connected components in a single jq pass.
# Algorithm: iteratively merge two contracts whose touches_files intersect, until
# no merges happen. O(N^2 * F) -- fine for plan sizes we expect (≤ ~30 contracts).
groups_json=$(jq -c '
  def merge_step(comps):
    # Try to merge first pair of overlapping components; return [merged, changed].
    . as $cs
    | (range(0; ($cs|length)) as $i
       | range($i+1; ($cs|length)) as $j
       | if (($cs[$i].files) - (($cs[$i].files) - ($cs[$j].files))) | length > 0
         then
           [ [$i, $j] ]
         else empty end) // null
    ;

  def merge_until_stable:
    . as $cs
    | ([range(0; ($cs|length)) as $i
        | range($i+1; ($cs|length)) as $j
        | select((($cs[$i].files) - (($cs[$i].files) - ($cs[$j].files))) | length > 0)
        | [$i, $j]
       ] | first) as $pair
    | if $pair == null then .
      else
        ($pair[0]) as $i | ($pair[1]) as $j
        | ([.[$i].names + .[$j].names | unique] | .[0]) as $merged_names
        | ([.[$i].files + .[$j].files | unique] | .[0]) as $merged_files
        | ([{names: $merged_names, files: $merged_files}]
           + [range(0; length) | select(. != $i and . != $j) | $cs[.]])
        | merge_until_stable
      end
    ;

  [.contracts[] | {names: [.name], files: (.touches_files // [])}]
  | merge_until_stable
' "$CONTRACTS_FILE")

# Translate components into shards.json with sequential letter ids.
shards_json=$(jq -n --argjson comps "$groups_json" '
  ($comps | length) as $n
  | def letter_id($i):
      if $i < 26 then [65 + $i] | implode
      else "S" + ($i|tostring) end;
  {
    schema_version: 1,
    fan_out_count: $n,
    groups: (
      [range(0; $n)] | map({
        key: letter_id(.),
        value: {
          shard_id: letter_id(.),
          contracts: $comps[.].names,
          files: $comps[.].files
        }
      }) | from_entries
    )
  }
')

echo "$shards_json" | jq '.' > "$SHARDS_FILE"

# Seed per-shard skeleton dirs + env.sh.
mkdir -p "$SHARDS_DIR"

# Source flow env to pick up parent SESSION's vars (for inheritance).
if [ -f "$flow_session/env.sh" ]; then
  # shellcheck disable=SC1090,SC1091
  . "$flow_session/env.sh"
fi

shard_ids=$(jq -r '.groups | keys[]' "$SHARDS_FILE")
for sid in $shard_ids; do
  shard_dir="$SHARDS_DIR/$sid"
  mkdir -p "$shard_dir/pi-sessions"

  # Per-shard env.sh: inherits parent SESSION vars, overrides SESSION + SESSION_BASENAME
  # so cf-pi-* scripts treat the shard dir as a session.
  #
  # CRITICAL: do NOT seed REPO_ROOT / BASE_BRANCH / BASE_HEAD. Those are written
  # by cf-pi-worktree.sh on first run for the shard; pre-seeding REPO_ROOT (even
  # empty) trips worktree.sh's grep-based idempotency guard and the per-shard
  # worktree is never created. (See bug fix log.)
  cat > "$shard_dir/env.sh" <<EOF
# Auto-generated by cf-pi-shard.sh -- per-shard session env
# Inherits from parent flow session, overrides SESSION + SESSION_BASENAME.
# REPO_ROOT/BASE_BRANCH/BASE_HEAD are appended by cf-pi-worktree.sh on first run.
FLOW_SESSION="$flow_session"
SHARD_ID="$sid"
SESSION="$shard_dir"
SESSION_BASENAME="${SESSION_BASENAME:-$(basename "$flow_session")}-shard-$sid"
PLUGIN_ROOT="${PLUGIN_ROOT:-}"
SCRIPTS="${SCRIPTS:-$SCRIPT_DIR}"
PI_PROTOCOL="${PI_PROTOCOL:-}"
CLEANUP_SCRIPT="${CLEANUP_SCRIPT:-}"
PI_PROVIDER="${PI_PROVIDER:-}"
PI_MODEL="${PI_MODEL:-}"
PI_DESC="${PI_DESC:-}"
PI_STALL_THRESHOLD_S="${PI_STALL_THRESHOLD_S:-180}"
PI_WALL_CLOCK_S="${PI_WALL_CLOCK_S:-1800}"
PI_AVAILABLE="${PI_AVAILABLE:-1}"
EOF
done

echo "shards.json: $SHARDS_FILE"
echo "fan_out_count: $(jq -r '.fan_out_count' "$SHARDS_FILE")"
jq -r '.groups | to_entries[] | "  \(.key): contracts=\(.value.contracts | length) files=\(.value.files | length)"' "$SHARDS_FILE"
