import { expect, test } from 'claude-code/testing'
import * as out from '../hooks/cli-output.ts'
const run = (stdout: string, exitCode = 0, stderr = '') => ({ kind: 'exited' as const, exitCode, stdout, stderr })
const closed = 'The CLI is unable to find Obsidian. Please make sure Obsidian is running and try again.\n'
test('removes legacy search output but keeps reads', () => { expect('searchOutput' in out).toBe(false); expect('readOutput' in out).toBe(true) })
test('recognizes dashboard rows by raw path and status', () => expect(out.baseQueryOutput(run('[{"path":"pm/p/tasks/a.md","Title":"A","status":"todo"}]'))).toEqual({ kind: 'rows', rows: [{ path: 'pm/p/tasks/a.md', status: 'todo' }] }))
test('keeps null and absent dashboard statuses', () => { expect(out.baseQueryOutput(run('[{"path":"pm/p/tasks/x.md"}]'))).toEqual({ kind: 'rows', rows: [{ path: 'pm/p/tasks/x.md', status: null }] }); expect(out.baseQueryOutput(run('[]'))).toEqual({ kind: 'empty' }) })
test('rejects malformed or failed dashboard output', () => { expect(out.baseQueryOutput(run('[{"path":3}]')).kind).toBe('error'); expect(out.baseQueryOutput(run('', 1, closed))).toEqual({ kind: 'error', message: closed.trim() }); expect(out.baseQueryOutput({ kind: 'rejected' }).kind).toBe('error') })
test('reads valid dashboard view names only', () => { expect(out.viewsOutput(run('Active\ttable\nCards\tcards\n'))).toEqual(['Active', 'Cards']); expect(out.viewsOutput(run('A\u001bB\ttable\nA\tB\ttable\nDocs\ttable\n'))).toEqual(['Docs']); expect(out.viewsOutput({ kind: 'rejected' })).toEqual([]) })
test('recognizes closed and empty frontmatter', () => { expect(out.readOutput(run('---\ntitle: x\n---\nbody'))).toEqual({ kind: 'card', frontmatter: 'title: x', body: 'body' }); expect(out.readOutput(run('---\n---\nbody'))).toEqual({ kind: 'card', frontmatter: '', body: 'body' }) })
test('rejects invalid read output', () => { expect(out.readOutput(run('Error: missing')).kind).toBe('error'); expect(out.readOutput(run('---\ntitle: x\n')).kind).toBe('error'); expect(out.readOutput(run('---\r\ntitle: x\r\n---\r\n')).kind).toBe('error'); expect(out.readOutput(run('', 1, closed))).toEqual({ kind: 'error', message: closed.trim() }); expect(out.readOutput({ kind: 'rejected' }).kind).toBe('error') })
test('closes only exact frontmatter dashes', () => expect(out.readOutput(run('---\na: 1\n----\n---\nbody'))).toEqual({ kind: 'card', frontmatter: 'a: 1\n----', body: 'body' }))
